public class ExceptionTest
{
    public static void main(String args[])
    {
         int j;
        for(int i=0;i<4;i++)
        {
            try
            {
                switch(i)
                {
                    case 0:int zero=0;
                    j=999/zero; //divide by zero error;
                    
                    case 1:int b[]=null;
                    j=b[0];  //Null pointer error
                    
                    case 2:
                        int c[]=new int[2];
                        j=c[10]; //array out of bound range
                        
                    case 3:
                        char ch="java".charAt(9);
                        break; //string out of bound range
                }
            }
            
            catch(Exception e)
            { 
                System.out.println("In test case #"+i);
                System.out.println(e.getMessage() );
                
            }
        }
    }
}    